# Simple workflow for deploying static content to GitHub Pages
name: Build Docs and Deploy static content to Pages

on:
  # For now only run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci
      - run: npm run build:docs  # Produces docs-html/ by running the script in package.json (yfm --input docs --output docs-html)
    
      # Upload the result as an artifact for the next job to use and deploy
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs-html
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deploy
        uses: actions/deploy-pages@v1
